SERVER_ERROR_MESSAGE = 'Internal Server Error';
AUTHENTICATION_FAILED_MESSAGE = 'Invalid username/password';
UNAUTHORIZED_USER_MESSAGE = 'User is not authorized';
USER_FOLLOWED_MESSAGE = 'User Followed';
USER_UNFOLLOWED_MESSAGE = 'User Unfollowed';
USER_NOT_FOUND = 'Invalid User';
LIKED_POST_MESSAGE = 'Post Liked';
UNLIKED_POST_MESSAGE = 'Post Unliked';
TITLE_REQUIRED_FOR_POST = 'Title Should not be empty';
INVALID_ID = 'Invalid id';

module.exports = {
	SERVER_ERROR_MESSAGE,
	AUTHENTICATION_FAILED_MESSAGE,
	UNAUTHORIZED_USER_MESSAGE,
	USER_FOLLOWED_MESSAGE,
	USER_NOT_FOUND,
	USER_UNFOLLOWED_MESSAGE,
	LIKED_POST_MESSAGE,
	UNLIKED_POST_MESSAGE,
	TITLE_REQUIRED_FOR_POST,
	INVALID_ID
};
