version: '3.9'
services:
    mongo_db:
        container_name: db_container
        image: mongo:latest
        restart: always
        volumes:
            - mongo_db:/data/db
    api:
        build: .
        ports:
            - 3000:3000
        environment:
            JWT_SECRET_KEY: THIS_IS_SUPER_SECRET_KEY_FOR_JWT
            NODE_ENV: prod
            MONGODB_URI_DEV: mongodb://mongo_db:27017/test
            MONGODB_URI_PROD: mongodb://mongo_db:27017/prod
            TEST_USERNAME: admin
            TEST_USERPASSWORD: admin@#123
            TEST_USERNAME2: test
        depends_on:
            - mongo_db

volumes:
    mongo_db: {}
